export const actions = {
  feedPost: {
    POST_FETCHING: "POST_FETCHING",
    POST_FETCHED: "POST_FETCHED",
    POST_FETCHING_ERROR: "POST_FETCHING_ERROR",
    POST_ADD_COMMENT: "POST_ADD_COMMENT",
    POST_ADD_LIKE: "POST_ADD_LIKE",
  },
};
